#!/bin/bash

PLUGIN_REPO_URL=$(git remote get-url origin)
BIN_PATH="~/.local/bin"
PLUGIN_PATH="~/.config/omarchy/plugins"
PLUGIN_NAME=$(basename -s .git "$PLUGIN_REPO_URL")
HYPRLAND_PLUGIN_FILE="~/.config/hypr/plugins.conf"

# Remove hyprland config sources
if [ -f "$HYPRLAND_PLUGIN_FILE" ] && [ -d "$PLUGIN_PATH/$PLUGIN_NAME/hypr" ]; then
  for file in "$PLUGIN_PATH/$PLUGIN_NAME/hypr"/*; do
    if [ -f "$file" ]; then
      # Remove the source line from hyprland config
      sed -i "\|source = $file|d" "$HYPRLAND_PLUGIN_FILE"
    fi
  done
fi

# Remove plugin
rm -rf "$PLUGIN_PATH/$PLUGIN_NAME"
