#!/bin/bash

PLUGIN_REPO_URL=$(git remote get-url origin)
BIN_PATH="$HOME/.local/bin"
PLUGIN_NAME=$(basename -s .git "$PLUGIN_REPO_URL")
PLUGIN_DIR="$HOME/.config/omarchy/plugins/$PLUGIN_NAME"
HYPRLAND_PLUGIN_FILE="$HOME/.config/hypr/plugins.conf"

# Remove hyprland config sources
if [ -f "$HYPRLAND_PLUGIN_FILE" ] && [ -d "$PLUGIN_DIR/hypr" ]; then
  for file in "$PLUGIN_DIR/hypr"/*; do
    if [ -f "$file" ]; then
      # Remove the source line from hyprland config
      sed -i "\|source = $file|d" "$HYPRLAND_PLUGIN_FILE"
    fi
  done
fi

# Remove plugin directory
rm -rf "$PLUGIN_DIR"
